# Generated by Django 5.2.7 on 2025-10-15 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('github', 'GitHub Repo'), ('json', 'JSON')], max_length=50)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='planner.project')),
            ],
            options={
                'db_table': 'export',
            },
        ),
    ]
