# Generated by Django 5.2.7 on 2025-10-15 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTemplate',
        ),
    ]
