# Generated by Django 5.2.7 on 2025-10-15 07:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('webapp', 'Web Application'), ('mobile', 'Mobile Application'), ('ai/ml', 'AI/ML Project'), ('data', 'Data Project'), ('developer_tool', 'Developer Tool'), ('automation_tool', 'Automation Tool')], max_length=50)),
                ('description', models.TextField()),
                ('default_sections', models.JSONField(default=dict)),
                ('default_diagrams', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_template',
            },
        ),
        migrations.RenameField(
            model_name='diagram',
            old_name='diagram_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
