# Generated by Django 5.2.7 on 2025-10-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_projecttemplate_rename_diagram_type_diagram_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='version',
            field=models.CharField(default='v1', max_length=50),
        ),
    ]
