# Generated by Django 5.2.7 on 2025-10-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_project_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order_index']},
        ),
    ]
