# Generated by Django 5.2.7 on 2025-11-10 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_section_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SectionVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_version', models.PositiveIntegerField()),
                ('section_version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('content_json', models.JSONField(default=dict)),
                ('order_index', models.IntegerField(default=0)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_versions', to='planner.project')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='planner.section')),
            ],
            options={
                'db_table': 'section_version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'project_version'], name='section_ver_project_136b23_idx'), models.Index(fields=['section'], name='section_ver_section_76b965_idx')],
                'unique_together': {('section', 'section_version')},
            },
        ),
    ]
